apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: csi-addons
  namespace: openshift-storage
  labels:
    operators.coreos.com/csi-addons.openshift-storage: ''
spec:
  channel: alpha
  config:
    tolerations:
      - effect: NoSchedule
        key: node.ocs.openshift.io/storage
        operator: Equal
        value: 'true'
  installPlanApproval: Automatic
  name: csi-addons
  source: odf-catalogsource
  sourceNamespace: openshift-marketplace
  startingCSV: csi-addons.v0.2.0
