apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  finalizers:
    - finalizer.operator.open-cluster-management.io
  name: multiclusterhub
  namespace: open-cluster-management
spec:
  availabilityConfig: High
  enableClusterBackup: false
  ingress:
    sslCiphers:
      - ECDHE-ECDSA-AES256-GCM-SHA384
      - ECDHE-RSA-AES256-GCM-SHA384
      - ECDHE-ECDSA-AES128-GCM-SHA256
      - ECDHE-RSA-AES128-GCM-SHA256
  separateCertificateManagement: false
